# Generated by Django 4.0.6 on 2022-07-25 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ppic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppic',
            name='related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userpic', to=settings.AUTH_USER_MODEL),
        ),
    ]
