# Generated by Django 4.0.6 on 2022-07-25 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='pupose',
            new_name='purpose',
        ),
    ]
