# Generated by Django 4.0.6 on 2022-07-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_rename_pupose_page_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.TextField(max_length=20, unique=True),
        ),
    ]
