# Generated by Django 4.0.6 on 2022-07-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_alter_page_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='top_image',
            field=models.ImageField(null=True, upload_to='pageimg/media'),
        ),
    ]
