# Generated by Django 4.0.6 on 2022-07-28 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_alter_page_top_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='top_image',
            field=models.ImageField(null=True, upload_to='pageimg/'),
        ),
    ]
