# Generated by Django 4.0.6 on 2022-08-01 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_alter_page_top_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TachiHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
            ],
        ),
    ]
