# Generated by Django 4.0.6 on 2022-08-01 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_page_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='page.tachihome'),
        ),
    ]
