# Generated by Django 4.0.6 on 2022-07-28 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_comment_author_alter_post_image_head_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_head',
            field=models.ImageField(blank=True, null=True, upload_to='postpic/'),
        ),
    ]
