# Generated by Django 4.0.6 on 2022-08-02 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_image_head'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='page',
            new_name='rpage',
        ),
    ]
