# Generated by Django 4.0.6 on 2022-08-02 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_rename_page_post_rpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='rpage',
            new_name='page',
        ),
    ]
