# Generated by Django 4.0.6 on 2022-07-28 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_fname_remove_customuser_lname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='ppic',
            field=models.ImageField(upload_to='ppics/'),
        ),
    ]
